opt_prompt_file = "my_prompt.Rmd"

include_files = '''
pipeline.md
'''
exclude_files = '''
*.toml
'''

template = '''

Below is code from selected R projects from my repbox / metareg toolbox.

# Package metaregBase

{{metaregBase}}

# Package repboxUtils

{{repboxUtils}}


# Package repboxStataReg

{{repboxStataReg}}

# Package repboxDRF

{{repboxDRF}}

# Package stata2r

{{stata2r}}

# Package regtranslate

{{regtranslate}}


##################################
# Your Task
##################################



'''



file_template = '''

# FILE: {{filename}}
```
{{filetext}}
```
# END OF FILE: {{filename}}

-----------------------------------------------------------
'''


[[metaregBase]]

include_files = '''
/home/rstudio/repbox/metaregBase/DESCRIPTION
/home/rstudio/repbox/metaregBase/R/*.R
'''


[[metaregTools]]

include_files = '''
/home/rstudio/repbox/metaregTools/DESCRIPTION
/home/rstudio/repbox/metaregTools/R/*.R
'''


[[repboxDRF]]

include_files = '''
/home/rstudio/repbox/repboxDRF/DESCRIPTION
/home/rstudio/repbox/repboxDRF/R/*.R
'''

[[regtranslate]]

include_files = '''
/home/rstudio/repbox/regtranslate/DESCRIPTION
/home/rstudio/repbox/regtranslate/R/*.R
'''


[[repboxUtils]]

include_files = '''
/home/rstudio/repbox/repboxUtils/DESCRIPTION
/home/rstudio/repbox/repboxUtils/R/*.R
'''

[[repboxStataReg]]

include_files = '''
/home/rstudio/repbox/repboxStataReg/DESCRIPTION
/home/rstudio/repbox/repboxStataReg/R/*.R
'''

[[stata2r]]

include_files = '''
/home/rstudio//aicoder/stata2r/DESCRIPTION
/home/rstudio//aicoder/stata2r//R/*.R
'''

