# metaregBase R run that
# runs regressions in R
# assume the base_r was already conducted and the
# corresponding parcels like regvar exist.

example = function() {
  library(metaregBase)
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"
  project_dir = "~/repbox/projects/test"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_load(project_dir)
  mrb = mrb_init(project_dir, drf=drf)

  if (FALSE) {
    mrb = mrb_full_stata_script(mrb)
    mrb = mrb_run_stata_script(mrb)
    mrb = mrb_agg_stata(mrb)
    mrb = mrb_run_r_base(mrb)
  }
  mrb = mrb_run_r_reg(mrb)
}

#' Run translated r regressions, store results and compare with Stata results
#' uses the parcels already generated by mrb_run_r_base and regtranslate for
#' regression translation
mrb_run_r_reg = function(mrb, just_pids=NULL) {
  restore.point("mrb_run_r_reg")

  mrb$artid = basename(mrb$project_dir)
  mrb$parcels = repboxDB::repdb_load_parcels(mrb$project_dir, c("reg_cmdpart", "reg","regvar","regxvar","regcoef", "regcoef_so"))

  pids = mrb$drf$pids
  if (length(pids) == 0) {
    cat("\nNo pids to process.\n")
    return(mrb)
  }

  all_pids = pids
  if (!is.null(just_pids)) {
    pids = just_pids
    mrb$is_partial_run = TRUE
    mrb$partial_pids = just_pids
  } else {
    mrb$is_partial_run = FALSE
  }

  all_step_parcels = list()

  cat("\nmrb_r_reg processing runids: ")
  for (pid in pids) {
    cat(paste0(pid," "))
    step_parcels = mrb_run_r_reg_step(mrb, pid)
    all_step_parcels[[as.character(pid)]] = step_parcels
  }
  cat("\n")
  mrb$all_step_parcels = all_step_parcels

  mrb = mrb_make_r_reg_parcels(mrb)

  mrb
}



#' Process a single regression, expand syntax, and format standard parcels
mrb_run_r_reg_step = function(mrb, pid) {
  restore.point("mrb_run_r_reg_step")

  project_dir = mrb$project_dir
  parcels = mrb$parcels
  artid = mrb$artid
  runid = pid

  reg = parcel_for_runid(parcels$reg, runid)
  regvar = parcel_for_runid(parcels$regvar, runid)
  regxvar = if (!is.null(parcels$regxvar)) parcel_for_runid(parcels$regxvar, runid) else tibble()
  cmdpart = parcel_for_runid(parcels$reg_cmdpart, runid)

  stata_co = parcel_for_runid(parcels$regcoef, runid)
  stata_co = stata_co[stata_co$variant == "sb", , drop = FALSE]
  stata_so = parcel_for_runid(parcels$regcoef_so, runid)
  default_eq = regcoef_default_eq(stata_co)

  step_parcels = list()

  diff_sb_so = NULL
  if (NROW(stata_co) > 0 && NROW(stata_so) > 0) {
     if (!"variant" %in% names(stata_co)) stata_co$variant = "sb"
     if (!"variant" %in% names(stata_so)) stata_so$variant = "so"
     diff_tab = coef_diff_table(stata_co, stata_so)
     if (!is.null(diff_tab)) {
        diff_sb_so = coef_diff_summary(diff_tab, compare_what=c("all","coef"))
     }
  }

  if (NROW(regvar) == 0 || NROW(cmdpart) == 0) {
    # Cannot translate if base parcels are empty, but we must return whatever diff we have
    step_parcels$regcoef_diff = diff_sb_so
    return(step_parcels)
  }

  library(regtranslate)
  opts = code_options(add_function = TRUE, add_broom = TRUE)
  code_df = try(reg_stata_to_r_code(reg, regvar, regxvar, cmdpart, prefer="fixest", opts=opts), silent=TRUE)

  reg_rb = reg %>% mutate(variant = "rb", error_in_r = FALSE, error_msg = "")

  if (is(code_df, "try-error") || any(grepl("# Stata command .* not fully translated", code_df$code)) || any(grepl("# Translation failed", code_df$code))) {
     reg_rb$error_in_r = TRUE
     reg_rb$error_msg = "Stata regression could not be translated to R."
     step_parcels$reg_rb = reg_rb
     step_parcels$regcoef_diff = diff_sb_so
     return(step_parcels)
  }

  code = paste0(code_df$code, collapse="\n")
  reg_fun_code = paste0("reg_fun = ", code)

  reg_fun = try(eval(parse(text=reg_fun_code)), silent=TRUE)
  if (is(reg_fun, "try-error")) {
     reg_rb$error_in_r = TRUE
     reg_rb$error_msg = "Error parsing translated R code."
     step_parcels$reg_rb = reg_rb
     step_parcels$regcoef_diff = diff_sb_so
     return(step_parcels)
  }

  # Fetch and prepare the data using our new refactored helper function
  dat = try(mrb_get_regression_data(runid, drf = mrb$drf, reg=reg, regvar = regvar, regxvar = regxvar), silent=TRUE)
  if (is(dat, "try-error")) {
     reg_rb$error_in_r = TRUE
     reg_rb$error_msg = "Error preparing regression data."
     step_parcels$reg_rb = reg_rb
     step_parcels$regcoef_diff = diff_sb_so
     return(step_parcels)
  }

  results = try(reg_fun(dat), silent=TRUE)
  if (is(results, "try-error")) {
     reg_rb$error_in_r = TRUE
     reg_rb$error_msg = as.character(attr(results, "condition")$message)
     step_parcels$reg_rb = reg_rb
     step_parcels$regcoef_diff = diff_sb_so
     return(step_parcels)
  }


  # Process R results
  ct = results$ct
  diff_sb_rb = NULL

  if (!is.null(ct) && nrow(ct) > 0) {
    ct$cterm = cterm_of_r_coefs(ct$term, regvar, dot_to_at = TRUE)
    co_df = ct_to_regcoef(ct, lang="r", variant="rb", artid=artid, default_eq=default_eq)
    co_df$runid = runid
    step_parcels$regcoef_rb = co_df

    # Comparison sb vs rb
    if (!is.null(stata_co) && nrow(stata_co) > 0) {
      if (!"variant" %in% names(stata_co)) stata_co$variant = "sb"
      diff_tab_rb = coef_diff_table(stata_co, co_df)
      if (!is.null(diff_tab_rb)) {
        diff_sb_rb = coef_diff_summary(diff_tab_rb, compare_what=c("all","coef"))
      }
    }
  }

  step_parcels$regcoef_diff = dplyr::bind_rows(diff_sb_so, diff_sb_rb)

  glance = results$glance

  if (!is.null(glance)) {
    glance$runid = runid
    glance$variant = "r"
    glance$artid = artid

    res_scalars = mrb_stats_to_regscalar_regstring(glance, variant="rb")
    if (!is.null(res_scalars$regscalar)) {
      step_parcels$regscalar_rb = res_scalars$regscalar
    }
    if (!is.null(res_scalars$regstring)) {
      step_parcels$regstring_rb = res_scalars$regstring
    }

    # Manual extraction of stats for reg table update
    stats = glance
    if ("r.squared" %in% names(stats)) stats$r2 = as.numeric(stats$r.squared)
    if ("adj.r.squared" %in% names(stats)) stats$adj_r2 = as.numeric(stats$adj.r.squared)
    if ("df.residual" %in% names(stats)) stats$df_r = as.numeric(stats$df.residual)
    if ("statistic" %in% names(stats)) stats$F = as.numeric(stats$statistic)

    stat_cols = intersect(c("r2", "adj_r2", "df_r", "F"), names(stats))
    for(col in stat_cols) {
      reg_rb[[col]] = stats[[col]]
    }
  }
  reg_rb$cmd = results$rcmd
  reg_rb$lang = "r"

  step_parcels$reg_rb = reg_rb

  return(step_parcels)
}


#' Get and prepare regression data (creates cterms and regxvar columns)
mrb_get_regression_data = function(runid, drf, reg=NULL, regvar, regxvar = NULL) {
  restore.point("mrb_get_regression_data")

  dat = repboxDRF::drf_get_data(runid, drf = drf)

  # CHANGE: Extract panel/time variables if available
  timevar = NA; panelvar = NA; tdelta = NA
  if (!is.null(reg) && nrow(reg) > 0) {
    timevar = reg$timevar[1]
    panelvar = reg$panelvar[1]
    tdelta = reg$tdelta[1]
  }

  if (!is.null(regvar) && nrow(regvar) > 0) {
    dat = create_cterm_cols(dat, unique(regvar$cterm),timevar = timevar,panelvar = panelvar, tdelta = tdelta)
  }

  if (!is.null(regxvar) && nrow(regxvar) > 0) {
    dat = make_regxvar_cols(dat, regxvar)
  }

  return(dat)
}

# The step parcels are generated in mrb_r
mrb_make_r_reg_parcels = function(mrb, save=TRUE,is_partial_run=mrb$is_partial_run) {
  restore.point("mrb_make_r_reg_parcels")

  if (is_partial_run) {
    mrb$parcels = repdb_load_parcels(mrb$project_dir, c("reg_rb","regcoef_rb","regcoef_diff","regscalar_rb","regstring_rb"))
  }


  parcels = list()
  all_step_parcels = mrb$all_step_parcels
  if (is.null(all_step_parcels)) {
    cat("\nAll step parcels were not generated in mrb.\n")
    return(mrb)
  }

  combine_steps = function(field) {
    res_list = lapply(all_step_parcels, function(x) x[[field]])
    res_list = res_list[!sapply(res_list, is.null)]
    if (length(res_list) == 0) {
      new_data = tibble()
    } else {
      new_data = bind_rows(res_list)
    }

    if (isTRUE(is_partial_run) && !is.null(mrb$parcels[[field]])) {
      old_data = mrb$parcels[[field]]
      if (NROW(old_data) > 0 && NROW(new_data) > 0) {
        old_kept = old_data[!old_data$runid %in% mrb$partial_pids, , drop = FALSE]
        new_data = bind_rows(old_kept, new_data)
      } else if (NROW(old_data) > 0 && NROW(new_data) == 0) {
        new_data = old_data
      }
    }

    if (NROW(new_data) > 0) {
      repdb_check_data(new_data, table=field)
    }
    new_data
  }

  parcels$reg_rb = combine_steps("reg_rb")
  parcels$regcoef_rb = combine_steps("regcoef_rb")
  parcels$regcoef_diff = combine_steps("regcoef_diff")
  parcels$regscalar_rb = combine_steps("regscalar_rb")
  parcels$regstring_rb = combine_steps("regstring_rb")

  # Save everything directly into the repdb directory
  if (save) {
    repdb_dir = file.path(mrb$project_dir, "repdb")
    repboxDB::repdb_save_parcels(parcels, repdb_dir, check = TRUE)
  }

  mrb$parcels[names(parcels)] = parcels
  return(mrb)
}




mrb_stats_to_regscalar_regstring = function(stats, runid=NULL, variant = NULL, omit_strings = c("cmdline","cmd","depvar","variant","artid"), omit_scalars = NULL) {
  restore.point("mrb_split_regscalar_regstring")
  stats = as_tibble(stats)

  cols = names(stats)
  char_cols = cols[sapply(stats, is.character)]
  num_cols = setdiff(cols, c(char_cols,"runid", omit_scalars))
  char_cols = setdiff(char_cols, omit_strings)

  if (length(char_cols)>0) {
    regstring = stats[,c("runid", char_cols)] %>%
      tidyr::pivot_longer(all_of(char_cols), names_to="string_name", values_to="string_val")
  } else {
    regstring = NULL
  }


  if (length(num_cols)>0) {
    stats[num_cols] = lapply(stats[num_cols], as.numeric)
    regscalar = stats[,c("runid", num_cols)] %>%
      tidyr::pivot_longer(all_of(num_cols), names_to="scalar_name", values_to="scalar_val")
  } else {
    regscalar = NULL
  }


  if (!"runid" %in% colnames(stats) & !is.null(runid)) {
    if (NROW(regstring)>0) regstring$step = runid
    if (NROW(regscalar)>0) regscalar$step = runid
  }

  if (!is.null(variant)) {
    if (!has_col(regstring, "variant") & NROW(regstring)>0) regstring$variant = variant
    if (!has_col(regscalar, "variant") & NROW(regscalar)>0) regscalar$variant = variant
  }

  if (NROW(regstring)==0) regstring = NULL
  if (NROW(regscalar)==0) regscalar = NULL

  list(regstring=regstring, regscalar=regscalar)

}

repdb_glance_to_reg_stats = function(glance) {
  stats = glance %>%
    add_coalesce("r2",c("r.squared")) %>%
    add_coalesce("adj_r2",c("adj.r.squared")) %>%
    add_coalesce("df_r",c("df.residual")) %>%
    add_coalesce("F",c("F","statistic"))
  stats[,intersect(c("artid","variant", "step", "r2","adj_r2","df_r","F"), colnames(stats))]
}

extract_reg_stats_from_regscalar = function(regscalar) {
  restore.point("extract_reg_stats_from_regscalar")

  stats = regscalar[, intersect(c("step","artid","variant"), colnames(regscalar))] %>%
    unique()

  stats
}








