# metaregBase R run that
# runs regressions in R
# assume the base_r was already conducted and the
# corresponding parcels like regvar exist.

example = function() {
  library(metaregBase)
  # Should point to this project dir
  project_dir = "~/repbox/projects/aejapp_11_2_10"
  project_dir = "~/repbox/projects/test"

  if (FALSE)
    rstudioapi::filesPaneNavigate(project_dir)

  drf = drf_load(project_dir)
  mrb = mrb_init(project_dir, drf=drf)

  if (FALSE) {
    mrb = mrb_full_stata_script(mrb)
    mrb = mrb_run_stata_script(mrb)
    mrb = mrb_agg_stata(mrb)
    mrb = mrb_run_r_base(mrb)
  }
  mrb = mrb_run_r_reg(mrb)
}

#' Run translated r regressions, store results and compare with Stata results
#' uses the parcels already generated by mrb_run_r_base and regtranslate for
#' regression translation
mrb_run_r_reg = function(mrb, just_pids=NULL) {
  restore.point("mrb_run_r_reg")

  mrb$artid = basename(mrb$project_dir)
  mrb$parcels = repboxDB::repdb_load_parcels(mrb$project_dir, c("reg_cmdpart", "reg","regvar","regxvar","regcoef"))

  pids = mrb$drf$pids
  if (length(pids) == 0) {
    cat("\nNo pids to process.\n")
    return(mrb)
  }
  if (!is.null(just_pids)) {
    pids = just_pids
  }

  all_step_parcels = list()

  for (pid in pids) {
    cat(sprintf("\nProcessing pid: %s", pid))
    step_parcels = mrb_run_r_reg_step(mrb, pid)
    all_step_parcels[[as.character(pid)]] = step_parcels
  }
  mrb$all_step_parcels = all_step_parcels

  mrb = mrb_make_r_reg_parcels(mrb)

  mrb
}


#' Process a single regression, expand syntax, and format standard parcels
mrb_run_r_reg_step = function(mrb, pid) {
  restore.point("mrb_run_r_reg_step")
  stop()

  project_dir = mrb$project_dir
  parcels = mrb$parcels
  artid = mrb$artid
  runid = pid

  reg = parcel_for_runid(parcels$reg, runid)
  regvar = parcel_for_runid(parcels$regvar, runid)
  regxvar = parcel_for_runid(parcels$regxvar, runid)
  cmdpart = parcel_for_runid(parcels$reg, runid)
  stata_co = parcel_for_runid(parcels$regcoef, runid)

  step_parcels = list()

  # Default regcheck and error state
  regcheck = tibble(runid = runid, problem = "", deviation = NA_real_, coef_deviation = NA_real_, identical = NA, identical_coef = NA)

  if (nrow(reg) == 0) {
    step_parcels$regcheck = regcheck %>% mutate(problem = "no reg parcel")
    return(step_parcels)
  }

  library(regtranslate)
  opts = code_options(add_function = TRUE, add_broom = TRUE)
  code_df = try(reg_stata_to_r_code(reg, regvar, regxvar, cmdpart, prefer="fixest", opts=opts), silent = TRUE)

  if (is(code_df, "try-error") || is.null(code_df) || nrow(code_df) == 0) {
    err_msg = if(is.null(code_df) || nrow(code_df) == 0) "No translation available" else as.character(code_df)
    reg_r = reg %>% mutate(variant = "r", error_in_r = TRUE, error_msg = err_msg)
    step_parcels$reg_r = reg_r
    step_parcels$regcheck = regcheck %>% mutate(problem = "translation failed")
    return(step_parcels)
  }

  code = paste0(code_df$code, collapse="\n")
  reg_fun_code = paste0("reg_fun = ", code)

  eval_res = try(eval(parse(text=reg_fun_code)), silent=TRUE)
  if (is(eval_res, "try-error")) {
    reg_r = reg %>% mutate(variant = "r", error_in_r = TRUE, error_msg = paste0("Failed to parse R code: ", as.character(eval_res)))
    step_parcels$reg_r = reg_r
    step_parcels$regcheck = regcheck %>% mutate(problem = "R code parsing failed")
    return(step_parcels)
  }

  dat = try(repboxDRF::drf_get_data(runid, drf = mrb$drf), silent=TRUE)
  if (is(dat, "try-error")) {
    reg_r = reg %>% mutate(variant = "r", error_in_r = TRUE, error_msg = paste0("Failed to load data: ", as.character(dat)))
    step_parcels$reg_r = reg_r
    step_parcels$regcheck = regcheck %>% mutate(problem = "data loading failed")
    return(step_parcels)
  }

  # Prepare data with created cterms and interaction columns
  dat = try({
    dat = create_cterm_cols(dat, unique(regvar$cterm))
    if (nrow(regxvar) > 0) {
      dat = make_regxvar_cols(dat, regxvar)
    }
    dat
  }, silent = TRUE)

  if (is(dat, "try-error")) {
    reg_r = reg %>% mutate(variant = "r", error_in_r = TRUE, error_msg = paste0("Failed to create cterms: ", as.character(dat)))
    step_parcels$reg_r = reg_r
    step_parcels$regcheck = regcheck %>% mutate(problem = "cterm creation failed")
    return(step_parcels)
  }

  results = try(reg_fun(dat), silent = TRUE)
  if (is(results, "try-error")) {
    reg_r = reg %>% mutate(variant = "r", error_in_r = TRUE, error_msg = paste0("Failed to run R regression: ", as.character(results)))
    step_parcels$reg_r = reg_r
    step_parcels$regcheck = regcheck %>% mutate(problem = "R regression failed")
    return(step_parcels)
  }

  # Process R results
  ct = results$ct
  if (!is.null(ct) && nrow(ct) > 0) {
    ct$cterm = cterm_of_r_coefs(ct$term, regvar, dot_to_at = TRUE)
    co_df = ct_to_regcoef(ct, lang="r", variant="r", artid=artid)
    co_df$runid = runid
    step_parcels$regcoef_r = co_df

    # Comparison
    if (!is.null(stata_co) && nrow(stata_co) > 0) {
      diff_tab = coef_diff_table(co_df, stata_co)
      if (!is.null(diff_tab)) {
        diff_sum = coef_diff_summary(diff_tab, compare_what=c("all","coef"))
        step_parcels$regcoef_diff = diff_sum

        diff_all = diff_sum %>% filter(compare_what == "all")
        diff_coef = diff_sum %>% filter(compare_what == "coef")

        if (nrow(diff_all) > 0) {
          regcheck$deviation = exp(0.5 * log(diff_all$max_rel_diff + 1e-12) + 0.5 * log(diff_all$max_deviation + 1e-12))
          regcheck$identical = diff_all$identical[1]
        }
        if (nrow(diff_coef) > 0) {
          regcheck$coef_deviation = exp(0.5 * log(diff_coef$max_rel_diff + 1e-12) + 0.5 * log(diff_coef$max_deviation + 1e-12))
          regcheck$identical_coef = diff_coef$identical[1]
        }
      }
    }
  } else {
    regcheck$problem = "no coefficients from R"
  }

  glance = results$glance
  reg_r = reg %>% mutate(variant = "r", error_in_r = FALSE, error_msg = "")

  if (!is.null(glance)) {
    glance$runid = runid
    glance$variant = "r"
    glance$artid = artid

    res_scalars = repdb_stats_to_regscalar_regstring(glance, variant="r", artid=artid)
    if (!is.null(res_scalars$regscalar)) {
      step_parcels$regscalar_r = res_scalars$regscalar
    }
    if (!is.null(res_scalars$regstring)) {
      step_parcels$regstring_r = res_scalars$regstring
    }

    # Manual extraction of stats for reg table update
    stats = glance
    if ("r.squared" %in% names(stats)) stats$r2 = as.numeric(stats$r.squared)
    if ("adj.r.squared" %in% names(stats)) stats$adj_r2 = as.numeric(stats$adj.r.squared)
    if ("df.residual" %in% names(stats)) stats$df_r = as.numeric(stats$df.residual)
    if ("statistic" %in% names(stats)) stats$F = as.numeric(stats$statistic)

    stat_cols = intersect(c("r2", "adj_r2", "df_r", "F"), names(stats))
    for(col in stat_cols) {
      reg_r[[col]] = stats[[col]]
    }
  }
  reg_r$cmd = results$rcmd
  reg_r$lang = "r"

  step_parcels$reg_r = reg_r
  step_parcels$regcheck = regcheck

  return(step_parcels)
}

# The step parcels are generated in mrb_r
mrb_make_r_reg_parcels = function(mrb, save=TRUE) {
  restore.point("mrb_make_r_reg_parcels")

  parcels = list()
  all_step_parcels = mrb$all_step_parcels
  if (is.null(all_step_parcels)) {
    cat("\nAll step parcels were not generated in mrb.\n")
    return(mrb)
  }

  combine_steps = function(field) {
    res_list = lapply(all_step_parcels, function(x) x[[field]])
    res_list = res_list[!sapply(res_list, is.null)]
    if (length(res_list) == 0) return(tibble())
    bind_rows(res_list)
  }

  parcels$reg_r = combine_steps("reg_r")
  parcels$regcoef_r = combine_steps("regcoef_r")
  parcels$regcoef_diff = combine_steps("regcoef_diff")
  parcels$regscalar_r = combine_steps("regscalar_r")
  parcels$regstring_r = combine_steps("regstring_r")
  parcels$regcheck = combine_steps("regcheck")

  # Save everything directly into the repdb directory
  if (save) {
    repdb_dir = file.path(mrb$project_dir, "repdb")
    repboxDB::repdb_save_parcels(parcels, repdb_dir, check = TRUE)
  }

  mrb$parcels[names(parcels)] = parcels
  return(mrb)
}










